#enable color to distinguish the file types
#below env vairables are used in ls command
export CLICOLOR=1
export LSCOLORS=DxfxcxdxCxegedabagacad
#enables color for iTerm
export TERM=xterm-color
#sets up proper alias commands when called
#


if [ -f ~/.alias ]; then
  . ~/.alias
fi

if [ -f ~/.git-completion.bash ]; then
  . ~/.git-completion.bash
fi

#customizing the prompt
# separte the current working directory with different color 
#export PS1="\e[0;31m[\u@\h\e[m \e[0;32m\w\e[m]\$"
# note that it is important to quote the color by escaped
# single square brackets, otherwise when you type a long
# command in terminal, it will eats previous line.
# http://stackoverflow.com/questions/5087036/bashrc-break-second-line-entered-in-shell-eats-up-first-line
red='\e[0;31m'
close='\e[m'
green='\e[0;32m'
blue='\e[0;34m'
cyan='\e[0;36m'
export PS1="\[$green\][\u@\v\[$close\] \[$blue\]\w\[$close\]]\$"
# Save and reload the history after each command finishes
export PROMPT_COMMAND="history -a; history -c; history -r; $PROMPT_COMMAND"

export HISTCONTROL=ignoredups:erasedups  # no duplicate entries
export HISTSIZE=100000                   # big big history
export HISTFILESIZE=100000               # big big history
shopt -s histappend                      # append to history, don't overwrite it

# only visible to myself
#umask 077
# umask 022

# check size of window, update COLUMNS and LINES if necessary
shopt -s checkwinsize

